#!/usr/bin/with-contenv bash

mkdir -p /config/crontabs

if [ ! -f /config/config.yml ]; then
    echo "**** First run detected. Initializing PlexTraktSync config.yml and printing info ****"
    chown abc:abc /config
    plextraktsync info
fi

if [ ! -f /config/crontabs/abc ]; then
    cp /defaults/abc /config/crontabs/abc
fi

rm -rf /etc/crontabs/abc
if [ -f /config/.env ] && [ -f /config/.pytrakt.json ]; then
    cp /config/crontabs/abc /etc/crontabs/abc
fi

lsiown -R abc:abc /config
