name: Check for base image updates

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * 0'

jobs:
  call-workflow:
    uses: linuxserver-labs/docker-actions/.github/workflows/check-baseimage-update.yml@v7.0.3
    with:
      repo_owner: ${{ github.repository_owner }}
      baseimage: "alpine"
      basebranch: "3.18"
      app_name: "plextraktsync"
    secrets:
      repo_release_token: ${{ secrets.repo_release_token }}
